meilisearch:
  api_url: http://meili:7700
  api_key: 'api-key'
  insert_size: 1000
  insert_interval: 10
source:
  type: postgres
  host: database
  port: 5431
  database: postgres
  user: postgres
  password: postgres
sync:
  - table: posts
    pk: id
    full: true
